config/routes.rb
Rails.application.routes.draw do
  resources :weight_classes
  resources :robots
  get 'robots/:id/speak/:message' => 'robots#speak', as: 'robot_speaks'

end

app/models/robot.rb
class Robot < ActiveRecord::Base
	belongs_to :weight_class
end

app/models/weight_class.rb
class WeightClass < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy, :speak]

  # GET /robots/:id/speak/:message
  def speak
	@message = params[:message]
  end
  
  # GET /robots
  # GET /robots.json
  def index
    @robots = Robot.all
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(robot_params)

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render :show, status: :created, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to @robot, notice: 'Robot was successfully updated.' }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to robots_url, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params.require(:robot).permit(:name, :weapon, :weight_class_id)
    end
end

app/controllers/weight_classes_controller.rb
class WeightClassesController < ApplicationController
  before_action :set_weight_class, only: [:show, :edit, :update, :destroy]

  # GET /weight_classes
  # GET /weight_classes.json
  def index
    @weight_classes = WeightClass.all
  end

  # GET /weight_classes/1
  # GET /weight_classes/1.json
  def show
  end

  # GET /weight_classes/new
  def new
    @weight_class = WeightClass.new
  end

  # GET /weight_classes/1/edit
  def edit
  end

  # POST /weight_classes
  # POST /weight_classes.json
  def create
    @weight_class = WeightClass.new(weight_class_params)

    respond_to do |format|
      if @weight_class.save
        format.html { redirect_to @weight_class, notice: 'Weight class was successfully created.' }
        format.json { render :show, status: :created, location: @weight_class }
      else
        format.html { render :new }
        format.json { render json: @weight_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_classes/1
  # PATCH/PUT /weight_classes/1.json
  def update
    respond_to do |format|
      if @weight_class.update(weight_class_params)
        format.html { redirect_to @weight_class, notice: 'Weight class was successfully updated.' }
        format.json { render :show, status: :ok, location: @weight_class }
      else
        format.html { render :edit }
        format.json { render json: @weight_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_classes/1
  # DELETE /weight_classes/1.json
  def destroy
    @weight_class.destroy
    respond_to do |format|
      format.html { redirect_to weight_classes_url, notice: 'Weight class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_class
      @weight_class = WeightClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_class_params
      params.require(:weight_class).permit(:name, :pounds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/weight_classes_helper.rb
module WeightClassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battlebots</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <div id="sitebanner">
	<h1>Mechanical Mayhem</h1>
  </div>
</head>
<body>
<header id="sitebanner">
	<h1>Mechanical Mayhem</h1>
</header>


<%= yield %>

</body>
</html>

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weapon %><br>
    <%= f.text_field :weapon %>
  </div>
  <div class="field">
    <%= f.label :weight_class %><br>
    <%= f.select(:weight_class_id, options_for_select(WeightClass.all.map { |wc| [wc.name, wc.id.to_i] })) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing Robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Robots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weapon</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @robots.each do |robot| %>
      <tr>
        <td><%= robot.name %></td>
        <td><%= robot.weapon %></td>
        <td><%= robot.weight_class.name %></td>
        <td><%= link_to 'Show', robot %></td>
        <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
        <td><%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Robot', new_robot_path %>

app/views/robots/new.html.erb
<h1>New Robot</h1>

<div id="newbotform">
	<%= render 'form' %>
</div>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <span id="botname"><%= @robot.name %></span>
</p>

<p>
  <strong>Weapon:</strong>
  <%= @robot.weapon %>
</p>

<p>
  <strong>Weight:</strong>
  <span id="weight_class"><%= @robot.weight_class.name %></span>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>

app/views/robots/speak.html.erb
<h1><%= @robot.name %> said...</h1>

<blockquote>
	<%= @message %>
</blockquote>

app/views/weight_classes/_form.html.erb
<%= form_for(@weight_class) do |f| %>
  <% if @weight_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight_class.errors.count, "error") %> prohibited this weight_class from being saved:</h2>

      <ul>
      <% @weight_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pounds %><br>
    <%= f.number_field :pounds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weight_classes/edit.html.erb
<h1>Editing Weight Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight_class %> |
<%= link_to 'Back', weight_classes_path %>

app/views/weight_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weight Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pounds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weight_classes.each do |weight_class| %>
      <tr>
        <td><%= weight_class.name %></td>
        <td><%= weight_class.pounds %></td>
        <td><%= link_to 'Show', weight_class %></td>
        <td><%= link_to 'Edit', edit_weight_class_path(weight_class) %></td>
        <td><%= link_to 'Destroy', weight_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weight class', new_weight_class_path %>

app/views/weight_classes/new.html.erb
<h1>New Weight Class</h1>

<%= render 'form' %>

<%= link_to 'Back', weight_classes_path %>

app/views/weight_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weight_class.name %>
</p>

<p>
  <strong>Pounds:</strong>
  <%= @weight_class.pounds %>
</p>

<%= link_to 'Edit', edit_weight_class_path(@weight_class) %> |
<%= link_to 'Back', weight_classes_path %>